### ISSUE TITLE
是否要引入模型加载库 Assimp

### ISSUE THREAD

**Issue by bobcao3** [IcebergOS/VM-76#10]
RT

**Comment by bobcao3** [comment]
http://assimp.sourceforge.net/main_downloads.html

**Comment by bobcao3** [comment]
https://github.com/assimp/assimp/releases/tag/v3.3.1/

**Comment by satgo1546** [comment]
“如果不引入的话，还有其他解决方案吗？”

引入越多复杂的库就越麻烦。毕竟我们这个是游戏，应该不会需要很多格式支持的。你看Audio，只能放个ogg vorbis。如果可以的话，我希望还是不要引入这种巨型文件格式库比较好——这会导致在Windoge上编译变得非常麻烦（所以我还有点想把SOIL替换成libpng（

当然了，不用这类库开发会有点麻烦。如果找不到特定的不那么庞大的加载模型的方案，引入assimp也（只能）是没有问题的。

**Comment by bobcao3** [comment]
加载库还是庞大点吧，blender啥的格式支持也不是很全，也许需要兼容性好的库。

（你试试编译一个？或者这个库放git submodule方便依赖关系

**Comment by satgo1546** [comment]
问题是我们反正也不会用什么奇怪的格式啊，模型首选当然.obj啦（

（这assimp还推荐要boost，然后一个boost就200MB
（虽说我确实不应该没有boost的

**Comment by bobcao3** [comment]
不用boost了，不就是载入快吗有啥用处

**Comment by satgo1546** [comment]
boost = performance boost :joy:
boost有这么没用吗 :joy:

**Comment by bobcao3** [comment]
我们也不太需要多线程加载。。这个我们都可以自己在加载的时候实现

**Comment by satgo1546** [comment]
经过了九天的努力（并不），这巨型lib终于被我编译出来了，libassimp.dll有5.98MB。
不过还算好，可以自己选择加入哪些格式的支持。上面这个是全加入后的。

**Comment by bobcao3** [comment]
New proposal:

做一个自己的模型描述格式，用ASM76内联数据表示顶点数据，材质文件等，用ASM76汇编来控制渲染行为等。然后用assimp做一个模型转换器

**Comment by satgo1546** [comment]
如果这样的话可能assimp都不需要了，完全可以直接写个Blender插件导出这种格式就可以了。（虽然我也不会写，这Python老是搞得我头大
而且似乎这种做法很不错的样子（核心原因是因为我们这游戏非常interestingly地做了个汇编233
主要问题就是可能又要搞个什么编辑器的……

**Comment by satgo1546** [comment]
是否要引入模型加载库Assimp？
——不引入

fixed
