### ISSUE TITLE
声音自动销毁和多重instance的。。bug？

### ISSUE THREAD

**Issue by bobcao3** [IcebergOS/VM-76#11]
你看右边gnome认为有多少个软件在播放声音，这是不是很滑稽x

![滑稽](http://i1.piimg.com/567571/55b193edc443997a.png)

**Comment by satgo1546** [comment]
大概是因为开了很多个stream？一个stream对一个软件吗……这么奇怪的设定啊（

那这得等哪天写个软件混音器才行了

反正还想着做3D音效呢（

**Comment by bobcao3** [comment]
混音有lib的吧

**Comment by satgo1546** [comment]
懒得翻lib干脆再造个轮子（

**Comment by satgo1546** [comment]
这个应该已经修好了吧？
