### ISSUE TITLE
ASM76

### ISSUE THREAD

**Issue by satgo1546** [IcebergOS/VM-76#13]
在做寒假作业的间隙悄悄咪咪溜出来讨论一下ASM76。

* 总体来说，因为我们这个汇编完全是为了好玩™，所以还是不要到处抄Intel为妙。
* LCMM默认居然有16KB？ ~~我建议改成0（滑稽），以增加LCMM指令的使用率。~~
    * 突然明白了这是坑。如果真是这样那就不改了。
* 我们需要为它定一个目标。
    * 为了坑玩家？为了装逼？为了……？
    * 并在指令集中处处体现。

**Comment by satgo1546** [comment]
### 参考资料

我在为PMVM（Planks Machine Virtual Machine）设计指令集的时候遵循的原则是“**坑**”。PMVM这个游戏是我以前造的一个大坑，但因为VM76的存在和其与之的重合度已经弃坑。为了坑而坑，它采用：仅有4个寄存器、字的范围是0..99、没有内存只有栈、二维格式指令。

我那时候指令用的是图像描述，现大致翻译成伪汇编。

* ADD - 运算在栈上操作。只有这一种双目数学运算。是的，没有SUB/IMUL/IDIV/IMOD。
* NEG - 栈顶数取反（99 - [SP]）。只有这一种单目数学运算。
* JC - 如果进位，控制流转入右侧；否则转入下侧。
* STC/CLC - 设置或清除进位标志。
* L/R/U/D - 转换执行方向。
* PUSH nn/R0/R1/R2/R3/[SP] - 压栈。
* POP (R0/R1/R2/R3) - 出栈。
* RET - 停止程序执行。

即便如此，还是能写程序？

```asm
; 1 + 2 + 3 + ⋯ + 10 = ?
D
PUSH 10
POP R0
PUSH R0
D	L
PUSH R0	ADD
PUSH 99	PUSH R0
ADD	POP R0
JC	U
POP	
RET
```

（之前上面这段汇编有BUG，现已修复）

胡乱翻译：

```asm
entry:
	MOV CX, 10
	MOV AX, 10
loop:
	DEC CX
	JZ end
	ADD AX, CX
	JMP loop
end:
	RET
```

不忍直视……

**Comment by bobcao3** [comment]
的确是有坑的，程序是被载入到local_memory然后执行的

突然意识到我们的程序指针是可读写的（（（
那么我们为啥需要JMP指令（（（（（

（不过为了效率还是别走RISC路线了。。我们刷不到那么高的MIPS的

分割线：

---

你看最新的commit，76-Base被全部完成了（不包括流程控制
所以我写个1到10求和的test吧（

---

目前没做编译器，所有的东西直接是堆在机器码的Struct里的
（不过通过那个struct的简洁程度你就会发现这个编译过程会多简单（
_HLT会中止运行
所有_HLT后面的代码可以当做.data区（完美解决字符串存储的问题

**Comment by bobcao3** [comment]
一测试果然有bug，修复推了

**Comment by satgo1546** [comment]
spec的Base部分就这么定了吗……这实现效率也太高了吧

那我去写个破解析器，然后真的就可以搞ASM程序了（然后项目语言统计里多出来个汇编（

**Comment by satgo1546** [comment]
我又有一言：我建议取消$86 ~ $99这些特殊寄存器，因为这破坏了完美的100个可用寄存器。改用$GT、$EQ、$LT、$SP、$PC之类的。我总感觉这种小坑没啥意思。要不，保留传统的话，从$101开始往上加如何？

另外，MINx/MTPx指令是故意这么拼的吗？

然后这个JMPR和JMPA确实可以不要了，直接MVRI $90, *x*多简单。

~~PS：好像spec里没有任何有立即数的指令。这“Store adress 0x00FF0000 to $0”也没法执行。这是坑吗？只能借助$86 ~ $99里预存的值，用数学运算指令得到所需数值？不敢想象。~~

DATx是仅有的立即数指令。我成功被坑了。我本以为那是跟汇编的DB/DW/DD一样的。

**Comment by satgo1546** [comment]
这个VM实现用了uint64_t之类的类型，就不能保证little-endian。虽说也不会真的在big-endian的机器上运行，但是还是要么不要在spec里写little-endian，要么把实现改成支持big-endian上的模拟little-endian为好。

**Comment by bobcao3** [comment]
汇编的DW/DD/DB直接留给编译器实现堆在Instruct里面就行，只要搞好对齐

---

对于端序的问题，目前先默认LE，之后加上#DEFINE MACHINE_BIG_ENDINE和对应的处理指令

**Comment by bobcao3** [comment]
其实把特殊寄存器也放在一起是为了操作方便
毕竟我们是虚拟CPU，不像真实CPU有各种电路坑，所以还是把内存的功能利用起来为好
不过可以加到$100+（反正不差这个内存

**Comment by satgo1546** [comment]
这个端序恐怕已经改不回来了，因为完全得另外做一套实现的样子

---

好就这么定了，就加到$100+上去
