### ISSUE TITLE
Vulkan : Should we support it?

### ISSUE THREAD

**Issue by bobcao3** [IcebergOS/VM-76#15]
如你所见，我们目前的渲染结构还算干净，做Vulkan支持应该不算复杂。我们只需要更高一级的抽象。在基本渲染原理上，包括顶点缓冲啥的Vulkan和OpenGL没啥区别，最大的区别在于渲染drawcall的API上。我认为Vulkan的异步能力对我们是很有用的

**Comment by satgo1546** [comment]
Why not?
不过我到现在还是没搞明白现在的渲染模型（

**Comment by bobcao3** [comment]
我决定先改进渲染模型再考虑Vulkan的事情
