### ISSUE TITLE
VMDE的公开讨论

### ISSUE THREAD

**Issue by satgo1546** [IcebergOS/VM-76#4]
待解决讨论之事，包括设计问题。随时可以补充。
- [x] 3D还是2D？
- [x] 纹理！纹理！纹理！名称叫Draw Engine，然而Draw的部分尚还不能画图片……
  - [x] 用什么图片格式？这个问题其实没啥好问的，因为我们有天下无敌的PNG。
  - [x] 导入其库。比如libpng。
  - [x] 把load_img填完……
- [x] 音频
  - [x] 采样率问题。关键是48000Hz怎么和44100Hz相互转换。这种问题应该许多人都问过。
  - [x] 是否需要特别的音量控制？
- [x] 文字绘制
  - [x] 如何画文字呢？位图字体还是FreeType？
  - [x] 有需要用户自己输入的地方吗？

\# @bobcao3 Cryst这种协作项目那边其实也可以开一个这样的issue玩

↑ 那个 # 被当成一级标题一直没被发现

**Comment by bobcao3** [comment]
文字我觉得
还是FreeType的
我们是中国人，位图到时候比谁都蛋疼（

**Comment by satgo1546** [comment]
你看Minecraft直接位图开满Unicode BMP一样用（x

**Comment by satgo1546** [comment]
> 有需要用户自己输入的地方吗？

废话，当然有。

这个issue完结。撒花！ :tada:
