### ISSUE TITLE
纪念用issue（II）

### ISSUE THREAD

**Issue by satgo1546** [IcebergOS/VM-76#7]
![Ｅｘｃｉｔｅｄ！](https://cloud.githubusercontent.com/assets/5250054/20037051/e25b9772-a453-11e6-870a-71c84c865679.png)

**Comment by bobcao3** [comment]
实际上我在尝试让引擎变地灵活，这样就可以符合原本太空游戏的主题了（
我在做类似Chunk的东西（我这边叫Structure），这样也许我们能创建出独立于世界方格的飞船什么的

**Comment by satgo1546** [comment]
几乎所有原本计划中的物件都是独立于方块而存在的……

还有为什么你那边叫Structure……

我刚刚push了。我**觉得**make.rb可以用了。

我可能有干了点结构改动，同时merge+手抖提交到了master上。

**Comment by bobcao3** [comment]
01/08 2017
同样的东西出现在了游戏里

只不过这一次有了烘培，也不再是硬编码的草地了（
