### ISSUE TITLE
声音模块的float → int之旅

### ISSUE THREAD

**Issue by satgo1546** [IcebergOS/VM-76#9]
当初干嘛用float呢？浪费一倍的内存，效果还不一定有int好。

虽然是这么说的，但是float现在哪里不好了？

- [ ] play_wave
	- [ ] triangle
	- [ ] sine
	- [ ] white_noise
- [ ] play_sound
	- [ ] play_sound
	- [ ] play_loop

**Comment by bobcao3** [comment]
float就float吧，反正编译开关开到sse4了用点float说不定还能SMID优化

**Comment by satgo1546** [comment]
:+1: 成功增加了偷懒的理由。
